### ISSUE TITLE
License inconsistency for header files

### ISSUE THREAD

**Issue by jettan** [AIS-Bonn/opt_control#3]
Hi there again!
Thank you so much for releasing the C++ static library.

I noticed that while the repo is under the BSD-3 license, the include headers mention that they are Student License only (perhaps because of Matlab code autogeneration).

**Comment by gavanderhoorn** [comment]
I'm actually wondering whether those headers can be relicensed as BSD. If they indeed come from the matlab codegen packages.

**Comment by MariusBeul** [comment]
In my opinion, the following excerpts from the MATLAB license applies:

- Certain Programs, such as the MATLAB Compiler and the Coder Programs,
generate output in the form of Source Code, Object Code, or other files and
materials. For example, the MATLAB Compiler can be used to create an
executable program, and MATLAB Coder and other Coder Programs can be used
to generate Source Code in C and C++. Under certain circumstances described
below, you are permitted to use and distribute the files, models,
Applications, and Generated Forms that you create using the Programs.

- No further license or royalty fees shall be due to MathWorks for
deployment as expressly permitted in this Section, regardless of whether
the deployment is solely for your Internal Operations or to Third Parties.

- You may only copy, modify, and deploy these proprietary MathWorks files
in Source Code or Linked Object Code form for different development targets
when used with the Coder Programs or with code generated by the Coder
Programs as part of, and only as required by, a larger standalone
application. A standalone application is an Application created using
programming languages and tools other than the Programs, which executes
outside of the Programs.

Am Mi., 29. Aug. 2018 um 13:04 Uhr schrieb G.A. vd. Hoorn <
notifications@github.com>:

**Comment by gavanderhoorn** [comment]
That makes it possible to distribute these files, but I don't see relicensing being mentioned there.

**Comment by MariusBeul** [comment]
Just to be sure I replaced the original comment in the included files.
