### ISSUE TITLE
optimization result status

### ISSUE THREAD

**Issue by eppravitra** [AIS-Bonn/opt_control#7]
What is the best way to retrieve the status of the optimization?
As in, which variable from opt_control_lib() should I read to know if the optimization succeeded?

I know there are print outs, but I want to use this status for other purposes.

Thanks for the library!

**Comment by MariusBeul** [comment]
Hi,
the algorithm is not optimizing the trajectory. Instead, it analytically solves the formulated problem. Hence, when the function returns, the trajectory was calculated successfully.
Was this answer helpful?

**Comment by eppravitra** [comment]
Hi Marius,

Thanks for the reply. I should have said. Is there a flag that returns when analytical solution does not exist, or which variable should I check to see if the solution is valid?

**Comment by MariusBeul** [comment]
Hi,

the method always returns a solution besides when

a) There is a formal error in the provided array sizes,
b) The trajectory is impossible to solve. E.g. when the waypoint velocity is outside of the V_max / V_min bound, etc.

In both cases, an error is thrown. On the other hand, if no error is thrown and the function returns successfully, the solution is valid and the variables encode a viable trajectory.

**Comment by eppravitra** [comment]
Thanks Marius

My question is how do I check if the error is thrown. For example, I want to do something like 

`opt_control_lib(State_start_in, Waypoints_in, V_max_in, V_min_in, A_max_in, A_min_in, J_max_in, J_min_in, A_global_in, b_comp_global_in, b_sync_V_in, b_sync_A_in, b_sync_J_in, b_sync_W_in, b_rotate_in, b_best_solution_in, b_hard_vel_limit_in, b_catch_up_in, solution_in, ts_rollout, J_setp_struct, solution_out, T_waypoints, P_rollout, V_rollout, A_rollout, J_rollout, t_rollout);
  
if (..there is error){
...do something....
}
`

The question is how do I check for error. What would go in the if statement? Will something like solution_out gives me that?

**Comment by eppravitra** [comment]
``

**Comment by MariusBeul** [comment]
Hi, 

you can use a try/catch statement in matlab: [ https://www.mathworks.com/help/matlab/ref/try.html | https://www.mathworks.com/help/matlab/ref/try.html ] 

The integer "solution_out" decodes properties of the trajectory to answer questions like 
- Does the trajectory reach maximum velocity? 
- Does the trajectory reach minimum acceleration? 
- Does the trajectory start in a feasibile start state? 
- ... 

Since the mapping between "solution_out" and the trajectory properties currently changes sometimes, currently it is not published. I think this would generate more confusion than it is useful. 
However, solution_out is always negative (-1,-2) when an error occurs. 


Best, 
Marius
